/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lightoff_pech_version_console;

import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
/**
 *
 * @author Camille
 */
public class FenetrePrincipale extends javax.swing.JFrame {
    GrilleDeCellules grille;
    private int nbCoups;
    int i;
    int a;
    /**
     * Creates new form FenetrePrincipale
     */
    public FenetrePrincipale() {
        
        initComponents();
        //initialiserPartie();
      
        
 


    }
    public void initialiserPartie(int nbLignes, int nbColonnes) {
        nbCoups = 0;
        getContentPane().add(PanneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70,
        nbColonnes*40, nbLignes*40));
        this.pack();
        this.revalidate();

        PanneauBoutonsVerticaux.setLayout(new GridLayout(nbLignes, 1));
        getContentPane().add(PanneauBoutonsVerticaux, new
        org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 1 * 40, nbLignes * 40));
        this.pack();
        this.revalidate();
        // création du panneau de boutons verticaux (pour les lignes)
     
        for ( i = 0; i < nbLignes; i++) {
        JButton bouton_ligne = new JButton();
        bouton_ligne.setBackground(Color.WHITE);
        ActionListener ecouteurClick = new ActionListener() {
        final int j = i;
        @Override
        public void actionPerformed(ActionEvent e) {
        grille.activerLigneDeCellules(j);
        
        
        repaint();
        Partie();
        }
        };
        bouton_ligne.addActionListener(ecouteurClick);
        PanneauBoutonsVerticaux.add(bouton_ligne);

        }
        PanneauBoutonsHorizontaux.setLayout(new GridLayout(1, nbColonnes));
        getContentPane().add(PanneauBoutonsHorizontaux, new
        org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, nbColonnes * 40, 1 * 40));
        this.pack();
        this.revalidate();
        for (a = 0; a < nbColonnes; a++) {
        JButton bouton_colonne = new JButton();
        bouton_colonne.setBackground(Color.WHITE);
        ActionListener ecouteurClick = new ActionListener() {
        final int b = a;
        @Override
        public void actionPerformed(ActionEvent e) {
        grille.activerColonneDeCellules(b);
        
       repaint();
       Partie();
        }
        };
        bouton_colonne.addActionListener(ecouteurClick);
        PanneauBoutonsHorizontaux.add(bouton_colonne);

        }
        this.grille = new GrilleDeCellules(nbLignes,nbColonnes);
        PanneauGrille.setLayout(new GridLayout(nbLignes, nbColonnes));
        for (int i=0; i < nbLignes; i++) {
        for (int j=0; j < nbColonnes; j++ ) {
        CelluleGraphique bouton_cellule = new CelluleGraphique( grille.matriceCellules[i][j], 360/nbLignes,360/nbColonnes);
        
        PanneauGrille.add(bouton_cellule); // ajout au Jpanel PanneauGrille
        
        getContentPane().add(diagmontante, new org.netbeans.lib.awtextra.AbsoluteConstraints(nbColonnes * 40+170, 20, 30, 30));
        grille.eteindreToutesLesCellules();
        grille.melangerMatriceAleatoirement(10);
        }}
        
         
        
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanneauGrille = new javax.swing.JPanel();
        PanneauBoutonsVerticaux = new javax.swing.JPanel();
        PanneauBoutonsHorizontaux = new javax.swing.JPanel();
        diagdescendante = new javax.swing.JButton();
        diagmontante = new javax.swing.JButton();
        nivfacile = new javax.swing.JButton();
        nivmoyen = new javax.swing.JButton();
        nivdiff = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        coups = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanneauGrille.setBackground(new java.awt.Color(255, 0, 153));

        javax.swing.GroupLayout PanneauGrilleLayout = new javax.swing.GroupLayout(PanneauGrille);
        PanneauGrille.setLayout(PanneauGrilleLayout);
        PanneauGrilleLayout.setHorizontalGroup(
            PanneauGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        PanneauGrilleLayout.setVerticalGroup(
            PanneauGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        getContentPane().add(PanneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 360, 360));

        PanneauBoutonsVerticaux.setBackground(new java.awt.Color(255, 0, 153));

        javax.swing.GroupLayout PanneauBoutonsVerticauxLayout = new javax.swing.GroupLayout(PanneauBoutonsVerticaux);
        PanneauBoutonsVerticaux.setLayout(PanneauBoutonsVerticauxLayout);
        PanneauBoutonsVerticauxLayout.setHorizontalGroup(
            PanneauBoutonsVerticauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        PanneauBoutonsVerticauxLayout.setVerticalGroup(
            PanneauBoutonsVerticauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        getContentPane().add(PanneauBoutonsVerticaux, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 50, 360));

        PanneauBoutonsHorizontaux.setBackground(new java.awt.Color(255, 0, 153));

        javax.swing.GroupLayout PanneauBoutonsHorizontauxLayout = new javax.swing.GroupLayout(PanneauBoutonsHorizontaux);
        PanneauBoutonsHorizontaux.setLayout(PanneauBoutonsHorizontauxLayout);
        PanneauBoutonsHorizontauxLayout.setHorizontalGroup(
            PanneauBoutonsHorizontauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        PanneauBoutonsHorizontauxLayout.setVerticalGroup(
            PanneauBoutonsHorizontauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(PanneauBoutonsHorizontaux, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 360, 50));

        diagdescendante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagdescendanteActionPerformed(evt);
            }
        });
        getContentPane().add(diagdescendante, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 30, 30));

        diagmontante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagmontanteActionPerformed(evt);
            }
        });
        getContentPane().add(diagmontante, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 30, 30));

        nivfacile.setText("FACILE");
        nivfacile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivfacileActionPerformed(evt);
            }
        });
        getContentPane().add(nivfacile, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, -1, -1));

        nivmoyen.setText("MOYEN");
        nivmoyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivmoyenActionPerformed(evt);
            }
        });
        getContentPane().add(nivmoyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, -1, -1));

        nivdiff.setText("DIFFICILE");
        nivdiff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivdiffActionPerformed(evt);
            }
        });
        getContentPane().add(nivdiff, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, -1, -1));

        coups.setEditable(false);
        coups.setBackground(new java.awt.Color(255, 204, 204));
        jScrollPane1.setViewportView(coups);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void Partie(){
        nbCoups ++;
        coups.setText("Nombre de coups : "+ nbCoups );
        if (grille.cellulesToutesEteintes()==true){
            FenetreVictoire f = new FenetreVictoire(nbCoups) ;
        
        f.setVisible(true);
        setVisible(false);
        }
    }
    private void diagdescendanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagdescendanteActionPerformed
        // TODO add your handling code here:
        diagdescendante.setBackground(Color.WHITE);
        grille.activerDiagonaleDescendante();
        
        repaint();
        Partie();
    }//GEN-LAST:event_diagdescendanteActionPerformed

    private void diagmontanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagmontanteActionPerformed
       diagmontante.setBackground(Color.WHITE);
       grille.activerDiagonaleMontante();
       
       repaint();// TODO add your handling code here:
       Partie();
    }//GEN-LAST:event_diagmontanteActionPerformed

    private void nivfacileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivfacileActionPerformed
        // TODO add your handling code here:
        initialiserPartie(6,6);
        nivfacile.setVisible(false);
        nivmoyen.setVisible(false);
        nivdiff.setVisible(false);
        
    }//GEN-LAST:event_nivfacileActionPerformed

    private void nivmoyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivmoyenActionPerformed
        initialiserPartie(10,10);
        nivfacile.setVisible(false);
        nivmoyen.setVisible(false);
        nivdiff.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_nivmoyenActionPerformed


    
    private void nivdiffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivdiffActionPerformed
        initialiserPartie(15,15);
        nivfacile.setVisible(false);
        nivmoyen.setVisible(false);
        nivdiff.setVisible(false);// TODO add your handling code here:// TODO add your handling code here:
    }//GEN-LAST:event_nivdiffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetrePrincipale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanneauBoutonsHorizontaux;
    private javax.swing.JPanel PanneauBoutonsVerticaux;
    private javax.swing.JPanel PanneauGrille;
    private javax.swing.JTextPane coups;
    private javax.swing.JButton diagdescendante;
    private javax.swing.JButton diagmontante;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nivdiff;
    private javax.swing.JButton nivfacile;
    private javax.swing.JButton nivmoyen;
    // End of variables declaration//GEN-END:variables
}
